Compatibility/vs code
xtjoeytx/GServer-v2 pull request #35
Opened 2021-03-08 16:52 UTC by 2ndwolf

Added VSCode compatibility through nuget package lookup (Findv8.cmake bigger and _badder_ will now inform of everything that's going on), a couple minor fixes and (hopefully) complete instructions for building on Windows using MSVC/MSBuild.

Tried to make it so it doesn't break on anyone else's toolchain, only adding mine.

Note that this will not work unless GS2lib is updated to add strsep, files were sent to Joey.

2021-03-11 11:03 UTC, xx-shitai-xx requested changes

2021-03-11 11:03 UTC, xx-shitai-xx commented on README.md
> +cd..
```suggestion
cd ..
```

2021-03-11 11:03 UTC, xx-shitai-xx commented on README.md
> +#### First, setup the environment:
```suggestion
#### Setup the environment:
```

2021-03-11 11:03 UTC, xx-shitai-xx commented on README.md
> +#### Then, running these commands should work.
```suggestion
#### Building the server with NPC-server support enabled
```

2021-03-11 11:03 UTC, xx-shitai-xx commented on CMakeLists.txt
> +		#add_subdirectory(${PROJECT_SOURCE_DIR}/cmake/v8)
```suggestion
```

2021-03-11 14:42 UTC, 2ndwolf commented on README.md
> +robocopy ..\packages\v8.redist-v142-x64.7.4.288.26\lib\Debug ..\bin\ *.bin
![image](https://user-images.githubusercontent.com/18505164/110804294-0b164180-824e-11eb-90ae-5b890f2a46b8.png)

2021-03-11 14:48 UTC, 2ndwolf commented on README.md
> +Add `D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\` to `VCTargetsPath` in your paths. Note that your actual installation path (folder in which `Microsoft Vi
Tbh, this wasn't my environment program files folder. The real one is on C. Microsoft Visual Studio doesn't force installation on %programfiles(x86)% and honestly shouldn't be installed there if C is an SSD with limited space like I have. Hence the note about installation path possibly being different; for the sake of completeness.

2021-03-11 14:56 UTC, 2ndwolf commented on README.md
> +git checkout feature/npc-server
Although it certainly won't the, readme and fix are on that particular branch... I wanted to supply commands that could be put in a batch file and build with little human intervention.

Not sure how to suggest a change but maybe something like
`git checkout (if-required)`
would work better

2021-03-11 16:05 UTC, xx-shitai-xx commented on README.md
> +git checkout feature/npc-server
since this gets committed to the feature/npc-server branch, it's moot nonetheless

2021-03-13 15:42 UTC, 2ndwolf commented on README.md
> +git checkout feature/npc-server
I don't think it's moot... I can easily imagine myself wondering why it doesn't work to realize so much later that I didn't `git checkout`. So a small reminder looks sensible to me.

2021-03-13 15:44 UTC, 2ndwolf commented on README.md
> +Add `D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\` to `VCTargetsPath` in your paths. Note that your actual installation path (folder in which `Microsoft Vi
I'll accept this, anyone who's into computers enough to compile a program should know that their installation paths may differ.

2021-03-14 02:21 UTC, 2ndwolf commented
Added a small collision fix. If that doesn't get the behaviour @xtjoeytx wants then it's not the right way to do it.

2021-03-15 10:10 UTC, merged